export type GraphAttachment = { filename: string; contentType: string; content: Buffer; };
export type GraphSendInput = { to: string | string[]; cc?: string | string[]; bcc?: string | string[]; subject: string; bodyText: string; bodyHtml?: string; attachments?: GraphAttachment[]; sendAs?: string; };
export type GraphSendResult = | { ok: true; messageId: string | null } | { ok: false; error: string; status?: number };
let cachedToken: { token: string; expiresAt: number } | null = null;
function envOrEmpty(k: string): string { return (process.env[k] ?? "").trim(); }
function asArray(s: string | string[] | undefined): string[] { if (!s) return []; return Array.isArray(s) ? s : [s]; }
function isConfigured(): { ok: true } | { ok: false; reason: string } { const missing: string[] = []; if (!envOrEmpty("MS_GRAPH_TENANT_ID")) missing.push("MS_GRAPH_TENANT_ID"); if (!envOrEmpty("MS_GRAPH_CLIENT_ID")) missing.push("MS_GRAPH_CLIENT_ID"); if (!envOrEmpty("MS_GRAPH_CLIENT_SECRET")) missing.push("MS_GRAPH_CLIENT_SECRET"); if (!envOrEmpty("MS_GRAPH_SEND_AS")) missing.push("MS_GRAPH_SEND_AS"); if (missing.length) return { ok: false, reason: `Missing env: ${missing.join(", ")}` }; return { ok: true }; }
export function logGraphConfigStatus(): void { const c = isConfigured(); if (c.ok) { console.log(`[graph] configured (send-as=${envOrEmpty("MS_GRAPH_SEND_AS")})`); } else { console.warn(`[graph] NOT configured — ${c.reason}. Email sends will fail.`); } }
async function getAccessToken(): Promise<string> { if (cachedToken && cachedToken.expiresAt > Date.now() + 60000) return cachedToken.token; const tenant = envOrEmpty("MS_GRAPH_TENANT_ID"); const clientId = envOrEmpty("MS_GRAPH_CLIENT_ID"); const clientSecret = envOrEmpty("MS_GRAPH_CLIENT_SECRET"); const url = `https://login.microsoftonline.com/${encodeURIComponent(tenant)}/oauth2/v2.0/token`; const body = new URLSearchParams({ client_id: clientId, client_secret: clientSecret, grant_type: "client_credentials", scope: "https://graph.microsoft.com/.default" }); const resp = await fetch(url, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }); if (!resp.ok) { const txt = await resp.text().catch(() => ""); throw new Error(`graph_token_failed status=${resp.status} body=${txt.slice(0, 300)}`); } const json = (await resp.json()) as { access_token?: string; expires_in?: number }; const token = String(json.access_token ?? ""); if (!token) throw new Error("graph_token_empty"); const expiresIn = Number(json.expires_in ?? 3600); cachedToken = { token, expiresAt: Date.now() + expiresIn * 1000 }; return token; }
export async function sendViaGraph(input: GraphSendInput): Promise<GraphSendResult> { const cfg = isConfigured(); if (!cfg.ok) return { ok: false, error: cfg.reason }; let token: string; try { token = await getAccessToken(); } catch (e) { return { ok: false, error: e instanceof Error ? e.message : String(e) }; } const sendAs = (input.sendAs ?? envOrEmpty("MS_GRAPH_SEND_AS")).trim(); if (!sendAs) return { ok: false, error: "send_as_missing" }; const message = { subject: input.subject, body: { contentType: input.bodyHtml ? "HTML" : "Text", content: input.bodyHtml ?? input.bodyText }, toRecipients: asArray(input.to).map((address) => ({ emailAddress: { address } })), ccRecipients: asArray(input.cc).map((address) => ({ emailAddress: { address } })), bccRecipients: asArray(input.bcc).map((address) => ({ emailAddress: { address } })), attachments: (input.attachments ?? []).map((a) => ({ "@odata.type": "#microsoft.graph.fileAttachment", name: a.filename, contentType: a.contentType, contentBytes: a.content.toString("base64") })) };
const url = `https://graph.microsoft.com/v1.0/users/${encodeURIComponent(sendAs)}/sendMail`; const resp = await fetch(url, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ message, saveToSentItems: true }) }); if (resp.status === 202) return { ok: true, messageId: null }; const txt = await resp.text().catch(() => ""); return { ok: false, status: resp.status, error: `graph_send_failed status=${resp.status} body=${txt.slice(0, 300)}` }; }
