-- Pre-seeds schema_migrations so the runner skips all 129 archived filenames.
-- On a fresh DB, 000_baseline.sql already created the full schema; this file
-- marks every archived name as applied so they are never run.
-- On an existing DB, 000_baseline.sql is caught by the idempotent error handler;
-- this file ensures all 129 legacy names are recorded and skipped going forward.
INSERT INTO schema_migrations (id) VALUES
('001_initial_schema.sql'),('002_contacts.sql'),('003_applications.sql'),
('004_documents.sql'),('005_chat.sql'),('006_lenders.sql'),
('007_ai_sessions.sql'),('008_analytics.sql'),('009_auth.sql'),
('010_settings.sql'),('011_users_status.sql'),('012_audit.sql'),
('013_notifications.sql'),('014_reporting.sql'),('015_schema_contracts.sql'),
('016_ocr.sql'),('017_auth_schema_repairs.sql'),
('018b_document_ocr_fields_bootstrap.sql'),('018c_ocr_results_fields.sql'),
('019_phone_unique.sql'),('020_ai_knowledge.sql'),('021_chat_messages.sql'),
('022_chat_queue.sql'),('023_user_status_flags.sql'),
('024_otp_verifications.sql'),('025_schema_mismatch_repairs.sql'),
('026_lenders.sql'),('027_create_lenders.sql'),
('028_users_o365_and_address.sql'),('029_lender_submissions.sql'),
('030_lender_schema_alignment.sql'),('031_lender_add_country_column.sql'),
('032_borrowers.sql'),('033_ai_rules.sql'),
('034_lender_products_type_status.sql'),
('035_create_lender_product_requirements.sql'),('036_ai_policy_rules.sql'),
('037_call_logs.sql'),('038_lender_status_pipeline_enum.sql'),
('039_pipeline_lender_enum_alignment.sql'),
('040_lender_product_country_rate.sql'),
('041_lender_schema_enforcement.sql'),('042_enum_alignment.sql'),
('043_call_logs.sql'),('044_live_chat.sql'),('045_issues.sql'),
('046_offers.sql'),('047_pwa.sql'),('048_readiness.sql'),
('049_voicemails.sql'),('050_lender_submission_method_config.sql'),
('051_document_reliability_phase3.sql'),('052_ai_embeddings.sql'),
('053_capital_readiness.sql'),('054_ops.sql'),
('055_document_processing_jobs.sql'),('056_export_audit.sql'),
('057_ai_voice_state.sql'),('058_processing_job_controls.sql'),
('059_job_retry_audit_views.sql'),('060_issue_reports.sql'),
('061_lender_documents.sql'),('062_continuation.sql'),
('063_ai_prequal.sql'),('064_crm_leads.sql'),('065_staff_presence.sql'),
('066_contact_leads.sql'),('067_chat_sessions_extended.sql'),
('068_ai_core_session_rag_crm.sql'),('069_crm_tasks.sql'),
('070_communications.sql'),('071_application_required_documents.sql'),
('072_application_continuations.sql'),('073_ai_knowledge_documents.sql'),
('074_pre_applications.sql'),('075_circuit_breaker.sql'),
('076_lender_submission_retries.sql'),('077_ai_system_rules.sql'),
('078_analytics_events.sql'),('079_pwa_notifications.sql'),
('080_chat_messages_content.sql'),('081_collateral.sql'),
('082_financials.sql'),('083_owners.sql'),('084_enum_consistency.sql'),
('085_application_stage_events.sql'),
('086_processing_jobs_control_plane.sql'),
('087_add_processing_job_tables.sql'),('088_add_job_tables_indexes.sql'),
('089_continuation_sessions.sql'),('090_otp_codes_no_pgcrypto.sql'),
('091_crm_timeline_events.sql'),('092_contacts_silo.sql'),
('093_communications_silo.sql'),('094_ai_escalations.sql'),
('095_crm_lead_activities.sql'),('096_notifications.sql'),
('097_application_updates.sql'),('098_messages_application_id.sql'),
('099_lender_products_amounts.sql'),('100_users_profile_columns.sql'),
('101_seed_lenders_products.sql'),('102_silo_and_profile_columns.sql'),
('103_application_startup_flag.sql'),('104_fix_all_migration_failures.sql'),
('105_seed_admin_users.sql'),('106_call_logs_schema.sql'),
('107_idempotency_repair.sql'),('108_call_logs_full_schema.sql'),
('109_lender_google_sheet.sql'),('110_schema_completion.sql'),
('111_add_media_category.sql'),('112_document_types.sql'),
('113_contacts_user_id.sql'),('114_readiness_sessions.sql'),
('115_application_processing_fields.sql'),('116_companies_table.sql'),
('117_lender_products_amounts_v2.sql'),('118_contacts_extended.sql'),
('119_ai_sessions_extended.sql'),('120_contacts_owner.sql'),
('121_lender_products_amount_min_max.sql'),
('122_applications_contact_company.sql'),
('123_applications_pipeline_processing.sql'),
('124_communications_extended.sql'),('125_contacts_tags.sql'),
('126_circuit_breaker_state.sql'),('127_ai_messages_session.sql'),
('128_lender_extended.sql'),('129_document_signed_category.sql'),
('201_view_rebuild.sql'),('999_indexes.sql')
ON CONFLICT (id) DO NOTHING;
