CREATE TABLE applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  business_name text NOT NULL,
  business_legal_name text NOT NULL,
  industry text NOT NULL,
  business_location text NOT NULL,
  years_in_business int NOT NULL,
  amount_requested int NOT NULL,
  avg_monthly_revenue int NOT NULL,
  revenue_last12m int NOT NULL,
  ar_balance int NOT NULL,
  ap_balance int NOT NULL,
  collateral_value int NOT NULL,
  funds_purpose text,
  status text NOT NULL,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);
