import { z } from "zod";

const boolString = z.enum(["true", "false"]);
const numericString = z.string().regex(/^\d+$/);

export const EnvSchema = z
  .object({
    NODE_ENV: z.enum(["development", "test", "production"]),
    DATABASE_URL: z.string().min(1),
    REDIS_URL: z.string().optional(),
    JWT_SECRET: z.string().min(10),
    OPENAI_API_KEY: z.string().min(1),
    ENABLE_TWILIO: boolString.optional(),
    TWILIO_ACCOUNT_SID: z.string().min(1).optional(),
    TWILIO_AUTH_TOKEN: z.string().min(1).optional(),
    TWILIO_PHONE: z.string().min(1).optional(),

    SENTRY_DSN: z.string().min(1).optional(),
    SLACK_ALERT_WEBHOOK_URL: z.string().min(1).optional(),

    PORT: numericString.optional(),
    API_BASE_URL: z.string().min(1).optional(),
    PUBLIC_BASE_URL: z.string().min(1).optional(),
    CLIENT_BASE_URL: z.string().min(1).optional(),
    LOG_LEVEL: z.string().min(1).optional(),
    INSTANCE_ID: z.string().min(1).optional(),
    HOSTNAME: z.string().min(1).optional(),
    APPINSIGHTS_CONNECTION_STRING: z.string().min(1).optional(),
    APPLICATIONINSIGHTS_CONNECTION_STRING: z.string().min(1).optional(),
    API_V1_ALLOW_UNFROZEN: boolString.optional(),
    RUN_DB_MIGRATIONS: boolString.optional(),
    SKIP_DB_CONNECTION: boolString.optional(),
    TWILIO_API_KEY: z.string().min(1).optional(),
    TWILIO_API_SECRET: z.string().min(1).optional(),
    TWILIO_VOICE_APP_SID: z.string().min(1).optional(),
    OTP_HASH_SECRET: z.string().min(1).optional(),
    GOOGLE_CLIENT_ID: z.string().min(1).optional(),
    GOOGLE_CLIENT_SECRET: z.string().min(1).optional(),
    GOOGLE_REDIRECT_URI: z.string().min(1).optional(),
    GOOGLE_SHEETS_REFRESH_TOKEN: z.string().min(1).optional(),

    BASE_URL: z.string().min(1).optional(),
    TEST_MODE: boolString.optional(),
    AUTH_DEBUG_OTP_PHONE: z.string().min(1).optional(),
    OTP_HASH_SALT: z.string().min(1).optional(),
    TEST_OTP_CODE: z.string().min(1).optional(),
    AZURE_OPENAI_DEPLOYMENT: z.string().min(1).optional(),
    AZURE_OPENAI_ENDPOINT: z.string().min(1).optional(),
    AZURE_OPENAI_KEY: z.string().min(1).optional(),
    AZURE_STORAGE_CONNECTION_STRING: z.string().min(1).optional(),
    BOOTSTRAP_ADMIN_PHONE: z.string().min(1).optional(),
    CLIENT_URL: z.string().min(1).optional(),
    CODESPACES: z.string().min(1).optional(),
    CODESPACE_NAME: z.string().min(1).optional(),
    GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN: z.string().min(1).optional(),
    CORS_ALLOWED_ORIGINS: z.string().min(1).optional(),
    CRM_WEBHOOK_URL: z.string().min(1).optional(),
    DB_HOST: z.string().min(1).optional(),
    DB_SSL: boolString.optional(),
    GOOGLE_SERVICE_ACCOUNT_EMAIL: z.string().min(1).optional(),
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: z.string().min(1).optional(),
    INTAKE_SMS_NUMBER: z.string().min(1).optional(),
    INTERNAL_API_KEY: z.string().min(1).optional(),
    ENABLE_INT_TEST_ROUTES: boolString.optional(),
    OPENAI_CHAT_MODEL: z.string().min(1).optional(),
    OPENAI_EMBED_MODEL: z.string().min(1).optional(),
    OPENAI_MODEL: z.string().min(1).optional(),
    AI_EMBED_MODEL: z.string().min(1).optional(),
    AI_MODEL: z.string().min(1).optional(),
    AI_SYSTEM_NAME: z.string().min(1).optional(),
    PORTAL_URL: z.string().min(1).optional(),
    PWA_PUSH_ENABLED: boolString.optional(),
    RATE_LIMIT_ENABLED: boolString.optional(),
    TWILIO_FROM: z.string().min(1).optional(),
    TWILIO_NUMBER: z.string().min(1).optional(),
    TWILIO_PHONE_NUMBER: z.string().min(1).optional(),
    TWILIO_VERIFY_SERVICE_SID: z.string().min(1).optional(),
    ALLOWED_ORIGINS: z.string().min(1).optional(),
    WEBSITE_URL: z.string().min(1).optional(),

    JWT_REFRESH_SECRET: z.string().min(1).optional(),
    JWT_ACCESS_EXPIRES_IN: z.string().min(1).optional(),
    JWT_REFRESH_EXPIRES_MS: numericString.optional(),
    DOCUMENT_MAX_SIZE_BYTES: numericString.optional(),
    DOCUMENT_ALLOWED_MIME_TYPES: z.string().min(1).optional(),
    OCR_TIMEOUT_MS: numericString.optional(),
    LENDER_RETRY_BASE_DELAY_MS: numericString.optional(),
    LENDER_RETRY_MAX_DELAY_MS: numericString.optional(),
    LENDER_RETRY_MAX_COUNT: numericString.optional(),
    FOLLOW_UP_INTERVAL_MS: numericString.optional(),
    FOLLOW_UP_ENABLED: boolString.optional(),
    RATE_LIMIT_WINDOW_MS: numericString.optional(),
    RATE_LIMIT_MAX: numericString.optional(),
    CLIENT_SUBMISSION_OWNER_USER_ID: z.string().min(1).optional(),

    COMMIT_SHA: z.string().min(1).optional(),
    BUILD_TIMESTAMP: z.string().min(1).optional(),
    IDEMPOTENCY_ENABLED: boolString.optional(),
    AUDIT_HISTORY_ENABLED: boolString.optional(),
    JWT_CLOCK_SKEW_SECONDS: numericString.optional(),
    AI_EMBEDDING_MODEL: z.string().min(1).optional(),
    OPENAI_OCR_MODEL: z.string().min(1).optional(),
    OCR_ENABLED: boolString.optional(),
    OCR_PROVIDER: z.string().min(1).optional(),
    OCR_MAX_ATTEMPTS: numericString.optional(),
    OCR_POLL_INTERVAL_MS: numericString.optional(),
    OCR_WORKER_CONCURRENCY: numericString.optional(),
    OCR_LOCK_TIMEOUT_MINUTES: numericString.optional(),
    PWA_SYNC_MAX_ACTIONS: numericString.optional(),
    PWA_SYNC_ACTION_MAX_BYTES: numericString.optional(),
    PWA_SYNC_BATCH_MAX_BYTES: numericString.optional(),
    PWA_PUSH_PAYLOAD_MAX_BYTES: numericString.optional(),
    VAPID_PUBLIC_KEY: z.string().min(1).optional(),
    VAPID_PRIVATE_KEY: z.string().min(1).optional(),
    VAPID_SUBJECT: z.string().min(1).optional(),
    RETRY_POLICY_ENABLED: boolString.optional(),
    REPORTING_JOBS_ENABLED: boolString.optional(),
    REPORTING_DAILY_INTERVAL_MS: numericString.optional(),
    REPORTING_HOURLY_INTERVAL_MS: numericString.optional(),
    VOICE_RESTRICTED_NUMBERS: z.string().optional(),
    OPS_KILL_SWITCH_REPLAY: boolString.optional(),
    OPS_KILL_SWITCH_EXPORTS: boolString.optional(),
    OPS_KILL_SWITCH_OCR: boolString.optional(),
    OPS_KILL_SWITCH_LENDER_TRANSMISSION: boolString.optional(),
  })
  .passthrough();

export type ParsedEnv = z.infer<typeof EnvSchema>;
