export const Errors = {
  INVALID_JSON: "INVALID_JSON",
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_PHONE: "INVALID_PHONE",
  INVALID_CODE: "INVALID_CODE",
  INVALID_TOKEN: "INVALID_TOKEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL: "INTERNAL_SERVER_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  OTP_START_FAILED: "OTP_START_FAILED",
  OTP_VERIFY_FAILED: "OTP_VERIFY_FAILED",
  SERVER_MISCONFIG: "SERVER_MISCONFIG",
} as const;

export type ErrorCode = (typeof Errors)[keyof typeof Errors];
