import { type Role, ROLES } from "./roles";

export const CAPABILITIES = {
  AUTH_SESSION: "auth:session",
  STAFF_OVERVIEW: "staff:overview",
  USER_MANAGE: "user:manage",
  APPLICATION_CREATE: "application:create",
  DOCUMENT_UPLOAD: "document:upload",
  DOCUMENT_REVIEW: "document:review",
  PIPELINE_MANAGE: "pipeline:manage",
  PIPELINE_OVERRIDE: "pipeline:override",
  LENDER_SUBMIT: "lender:submit",
  AUDIT_VIEW: "audit:view",
  ACCOUNT_UNLOCK: "account:unlock",
} as const;

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];

const roleCapabilities: Record<Role, readonly Capability[]> = {
  [ROLES.ADMIN]: [
    CAPABILITIES.AUTH_SESSION,
    CAPABILITIES.USER_MANAGE,
    CAPABILITIES.APPLICATION_CREATE,
    CAPABILITIES.DOCUMENT_UPLOAD,
    CAPABILITIES.DOCUMENT_REVIEW,
    CAPABILITIES.PIPELINE_MANAGE,
    CAPABILITIES.PIPELINE_OVERRIDE,
    CAPABILITIES.LENDER_SUBMIT,
    CAPABILITIES.AUDIT_VIEW,
    CAPABILITIES.ACCOUNT_UNLOCK,
  ],
  [ROLES.STAFF]: [
    CAPABILITIES.AUTH_SESSION,
    CAPABILITIES.STAFF_OVERVIEW,
    CAPABILITIES.APPLICATION_CREATE,
    CAPABILITIES.DOCUMENT_UPLOAD,
    CAPABILITIES.DOCUMENT_REVIEW,
    CAPABILITIES.PIPELINE_MANAGE,
    CAPABILITIES.PIPELINE_OVERRIDE,
    CAPABILITIES.LENDER_SUBMIT,
  ],
  [ROLES.USER]: [
    CAPABILITIES.AUTH_SESSION,
    CAPABILITIES.APPLICATION_CREATE,
    CAPABILITIES.DOCUMENT_UPLOAD,
  ],
};

export function getCapabilitiesForRole(role: Role): Capability[] {
  return [...(roleCapabilities[role] ?? [])];
}
