name: Deploy BF Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Type Check (FAILS BUILD IF BROKEN)
        run: npm run typecheck

      - name: Build (FAILS BUILD IF BROKEN)
        run: npm run build

      - name: Deploy
        run: echo "Deploy step here"
